# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  首页: /
  归档: /archives

# Default post title
default_post_title: 名字都没有你敢信

# Archive Date Format
archive_date_format: YYYY-MM-DD

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Social Accounts
twitter_url: https://twitter.com/marsoln1988
github_url: https://github.com/marsoln/my-blog
email_url: marsoln1988@gmail.com

# Footer About Text
footer_about: "如果有问题欢迎提ISSUE"

#Footer Copyright Line
footer_copyright: "Hexo & Alpha-Dust What A Magic! ❤ by Marsoln"